#!/bin/sh
#
# Start the DHCP server....
#

case "$1" in
  start)
 	echo "Starting DHCP server..."
	/usr/sbin/udhcpd 
	;;
  stop)
	echo -n "Stopping DHCP server..."
	killall udhcpd
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

